### ISSUE TITLE
Menu not appear if not apps installed on emulators

### ISSUE THREAD

**Issue by jesuslg123** [dsmelov/simsim#18]
SimSim is not showing any menu when clicking on the top bar icon if emulators has never run and there are no applications installed.

**Comment by dsmelov** [comment]
Could you please provide more information? Unfortunately I have no chance to reproduce this issue on my machine.

**Comment by jesuslg123** [comment]
If you have a fresh pc, my case today, I installed SimSim before start any
iOS project. When trying to explore the menu of SimSim, it was not showing
anything. After run a project on emulator, menu was shown property, even
after remove the application installed on the emulator, menu is working
fine, now shows emulator name without apps.

So I think there is some kind of issue if no emulator are found. After run
one emulator, its works fine.

**Comment by 2h4u** [comment]
I was able to reproduce the issue and fixed it. Pullrequest is incoming 😄

**Comment by dsmelov** [comment]
Thanks! I have no time for now to debug the app.

**Comment by 2h4u** [comment]
Welcome 😃 
I really like your app btw. I also tried the competition (openSim) but in my opinion simsim is better 😉
