### ISSUE TITLE
XCode 9.0 (9A235)- simsim doesnt open any menu

### ISSUE THREAD

**Issue by Briahas** [dsmelov/simsim#20]
HighSierra, XCode 9.0 (9A235), Build is the last - SimSim_1.3.0 (1).dmg

**Comment by 2h4u** [comment]
Try to check out the latest master and build it via xcode, what happens?

**Comment by DesmanLead** [comment]
Looks like the issue fixed in a638709e4bdbca4e4225c6884ad8f6bb1b901945.

@Briahas check version 1.3.1, please.

**Comment by 2h4u** [comment]
awesome 👍 

I'll update to HighSierra and check it

**Comment by dsmelov** [comment]
Guys, ArtemK released v1.3.2, please skip 1.3.1 and check the latest one.

**Comment by 2h4u** [comment]
Yeah of course, i'll let you know as soon as i'm done with updating/testing

**Comment by 2h4u** [comment]
![image](https://user-images.githubusercontent.com/4823365/31033627-0f7e3188-a561-11e7-939d-ce80005359b4.png)

Seems to work as expected 👍 
(macOS: 10.13 (17A365); xcode 9.0 (9A235))

**Comment by dsmelov** [comment]
Fixed in release 1.3.2.
