### ISSUE TITLE
A good suggestion

### ISSUE THREAD

**Issue by longjun-9** [dsmelov/simsim#24]
Could you add a mark to the using simulator? There are too many of them。Thank you~

**Comment by dsmelov** [comment]
Hi. 
1. Could you please provide more details - what do you mean by marks?
2. Which version of SimSim are you using? We added "show 5 recent simulators" in 1.3.3.
3. Please attach a screenshot with "too many of them".

**Comment by DesmanLead** [comment]
@longjun-9 since v1.3.3 simulators list is sorted by a last launch time. So current simulator will be on top of the list.

**Comment by longjun-9** [comment]
I see，thanks！
