### ISSUE TITLE
Limit options

### ISSUE THREAD

**Issue by rehannali** [dsmelov/simsim#27]
Hi, I want to know if there is any way to limit application like max latest 3 or 2 or something like that so I can restrict simulators as well as application to look clean. There is a lot of simulators and in simulators a lot of apps. I just want to know if there is anything to filter it or restrict it in some ways?
Thanks

**Comment by DesmanLead** [comment]
@rehannali check out version 1.3.3, please. Only 5 most recent simulators are presented there.

**Comment by rehannali** [comment]
@DesmanLead I actually want more customization like right now 5 most recent simulators are showing and i want more less i.e. 2 or 3 max. Like simulator, i want apps limitation to so everything should not be messed up.
I hope you understand.

**Comment by dsmelov** [comment]
@rehannali The only way to customize this option is to fork the project and modify MAX_RECENT_SIMULATORS in source code to suit your needs. We don't suppose to add any settings dialog at the moment.
