### ISSUE TITLE
iPhone X's app is listed reduplicated

### ISSUE THREAD

**Issue by ryderfang** [dsmelov/simsim#29]
<img width="371" alt="20180402152458" src="https://user-images.githubusercontent.com/5010519/38187438-3672c8e8-368a-11e8-9bc4-3449c0190bac.png">

as the pic shows.

**Comment by dsmelov** [comment]
Unable to reproduce. Please feel free to reopen the issue when you'll be able to provide more details.

**Comment by 2h4u** [comment]
I have the same problem since xcode 9, iPhone X is the only simluator which gets double listed.

![image](https://user-images.githubusercontent.com/4823365/38246507-461b8d3a-3742-11e8-9db0-65aedcc62ec7.png)

I'll see if I can provide a fix

**Comment by 2h4u** [comment]
Fixed the problem:
https://github.com/dsmelov/simsim/pull/30
