### ISSUE TITLE
App with no icon appears super large

### ISSUE THREAD

**Issue by apparition47** [dsmelov/simsim#33]
I'm on latest `5e5c5f9e148acf10631e06434933d1dcdebf9dbb` as I need App Groups support. I have an app installed in my simulator without a app icon. Looks like it's not being constrained to the proper size causing the dropdown to be oversized.

![screen_shot_2018-07-12_at_11_17_48](https://user-images.githubusercontent.com/3298414/42609011-798ceaca-85c5-11e8-94ab-bf667a133525.png)

P.S. wish the new App Groups function would show Realm too

**Comment by dsmelov** [comment]
Fixed in 8ac6977
