### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by punto2018** [dsmelov/simsim#35]
Hi,
I'm trying it with macOS 10.13.6 and xcode 10 and it simply crash.
Let me know if I can give you more info.

Thanks

**Comment by DesmanLead** [comment]
Could you reproduce the crash with a debugger attached, please?

**Comment by 2h4u** [comment]
@punto2018: 
I can't reproduce the crash. Could you download the simsim project and try to compile it with xcode? You should get a more detailed error explanation from the xcode console. With that we are probably able to fix the issue.

**Comment by punto2018** [comment]
Hi,
attached the crash using xcode.

<img width="1765" alt="schermata 2018-10-12 alle 09 18 23" src="https://user-images.githubusercontent.com/32935246/46853962-da711a00-cdff-11e8-8404-f19ed08363bc.png">

**Comment by punto2018** [comment]
I confirm that it now works fine, thanks!
