### ISSUE TITLE
Migrate from LSSharedFileList usage

### ISSUE THREAD

**Issue by DesmanLead** [dsmelov/simsim#41]
LSSharedFileList was deprecated in OS X 10.11.
Proposed alternatives:
LaunchAgent, XPCService or the ServiceManagement APIs.

Currently it is used for the "start at login" feature.
Look at `Settings.swift`

**Comment by vani2** [comment]
It looks like there is no better way to do that for apps outside AppStore https://stackoverflow.com/questions/57408051/how-to-add-loginitems-since-macos-10-11-when-lssharedfilelistinsertitemurl-is-de
