### ISSUE TITLE
reset Application not working anymore

### ISSUE THREAD

**Issue by SamiLechner** [dsmelov/simsim#44]
Hi 
i am using version 1.4.2 release. The feature "reset application data" which used to wipe the /Users/XXX/Library/Developer/CoreSimulator/Devices/..... /Documents folder is not working anymore. if I use the open in "finder" the right location is opened in finder.

hope that helps to track down the issue. 

Sami

**Comment by 2h4u** [comment]
I think this issue can be closed now
