### ISSUE TITLE
Strange empty menu items (no title) or strangely named menu items in 1.4.3 (206df9c)

### ISSUE THREAD

**Issue by altimac** [dsmelov/simsim#47]
As you can see in the attached picture some of the entries of SimSim seems wrong. I think they appeared recently with iOS 13? I'm post 1.4.3 release (commit 206df9c6723d1dae19949971b342808af91d69d7)
Can anyone advise?

Thanks for your valuable work!

<img width="396" alt="Screen Shot 2019-12-11 at 06 27 40" src="https://user-images.githubusercontent.com/778986/70594047-81596d80-1bdf-11ea-8020-d2bdd2befa6e.png">

**Comment by 2h4u** [comment]
I see the same elements as you do and I also think that this is related to iOS 13.
But I don't know if there is actually a use case for these elements or not, so I'm not a 100% sure if we can simple hide these elements all the time.

So if no one surely knows we could either create a setting for these elements to show or we could risk it and simple hide those elements all the time.

@contributers: Any suggestions?

**Comment by DesmanLead** [comment]
Siri Shortcuts appeared in iOS 13 and these app groups are somehow related to the Shortcuts app.
Does anyone here have an experience of deep integration with Siri Shortcuts? Is it handy to have an access to these folders?
It's not a problem to filter out these items if nobody needs them.

**Comment by altimac** [comment]
As v1.4.4 and iOS 13, I can't reproduce the problem.
